import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Link href={"/performance"}>Go to performance</Link>
                    <Link href={"/reliability/details"}>Go to reliability</Link>
                    <Link href={"/scale"}>Go to scale</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
